/** Categorised emoji library for the pill emoji picker.
 *  Each category has searchable `keywords` so the picker's search box can match
 *  a whole group (e.g. "money", "happy", "arrow", "food"). */
window.EMOJI_LIBRARY = [
  { name: 'Money', keywords: 'money cash currency dollar pound euro yen coin rich pay finance budget spend save',
    emojis: ['💵','💴','💶','💷','💰','💸','🪙','🤑','💲','💱','🏧','🏦','🪪','💳','🧾','🧮','📇','🆔','💎','🏷️'] },
  { name: 'Charts & growth', keywords: 'chart graph growth up down trend stats analytics increase decrease profit loss',
    emojis: ['📈','📉','📊','💹','🧗','⬆️','⬇️','↗️','↘️','🔼','🔽','⏫','⏬','🚀','📶','🌡️','🪜','🆙'] },
  { name: 'Goals & trophies', keywords: 'goal trophy win award medal first prize champion star success target rocket crown',
    emojis: ['🎯','🏆','🥇','🥈','🥉','🏅','🎖️','🎗️','🏵️','👑','🚀','🛫','⭐','🌟','✨','💫','🔝','🎆','🎇','🌠','🏁','🚩'] },
  { name: 'Rewards & gifts', keywords: 'gift reward bonus present bag shopping ticket voucher prize wrap',
    emojis: ['🎁','🎀','🛍️','👜','👛','👝','🧧','🎫','🎟️','🪅','🧸','💐','🎈','🪙'] },
  { name: 'Time & streaks', keywords: 'time clock streak day daily calendar repeat fire fast schedule deadline timer hourglass',
    emojis: ['⏰','⏱️','⏲️','⏳','⌛','🕐','🕑','🕒','🕓','📅','📆','🗓️','📇','🔁','🔂','🔄','♻️','🔥','⚡','💥','🌅','🌄','🌇','🌃'] },
  { name: 'Status & checks', keywords: 'check tick done yes no cross status dot circle ok new free done complete approve deny warning',
    emojis: ['✅','☑️','✔️','❌','❎','✖️','🟢','🟩','🔵','🟦','🟣','🟪','🟡','🟨','🟠','🟧','🔴','🟥','⚪','⚫','🟤','🟫','🔘','🔲','🔳','💯','📌','📍','❗','❓','❕','❔','‼️','⁉️','⚠️','🚫','⛔','🆗','🆕','🆓','🆙','🆒','🔝','🚦','🚥'] },
  { name: 'Security & privacy', keywords: 'lock secure security private privacy key shield safe protect hidden no bank mute',
    emojis: ['🔒','🔓','🔐','🔏','🗝️','🔑','🛡️','🦺','👁️','🙈','🙉','🙊','🤐','🤫','🚨','📵','🔕','🚷','🔇','⛓️','🧯'] },
  { name: 'Hands & gestures', keywords: 'hand thumb up down ok point clap wave pray fist strong like dislike high five muscle write',
    emojis: ['👍','👎','👌','🤌','🤏','✌️','🤞','🫰','🤟','🤘','🤙','👈','👉','👆','👇','☝️','✋','🤚','🖐️','🖖','👋','🤝','🙏','🫶','👏','🙌','🫵','💪','✍️','🤳','🫳','🫴','👐'] },
  { name: 'Smileys & faces', keywords: 'face smile happy laugh sad cry angry love cool wink think emotion mood shocked tired',
    emojis: ['😀','😃','😄','😁','😆','😅','😂','🤣','🙂','🙃','😉','😊','😇','🥰','😍','🤩','😘','😋','😛','😜','🤪','😝','🤗','🤔','🫡','🤨','🧐','😎','🥳','😏','😶','😐','🙄','😴','🤤','😪','😌','🥺','🥹','😢','😭','😤','😠','😡','🤯','😳','🥵','🥶','😱','😨','😰','🤥','🤓','🫠','🫢','🤭','😬','😵','🤒','🤕','🤧','😷'] },
  { name: 'Hearts & love', keywords: 'heart love like red pink purple blue green favourite romance care',
    emojis: ['❤️','🧡','💛','💚','💙','💜','🤎','🖤','🤍','🩷','🩵','🩶','💖','💗','💓','💞','💕','💘','💝','💟','❣️','💌','💋','💢','💥'] },
  { name: 'Mind, calm & wellness', keywords: 'calm mind idea brain zen relax peace yoga wellness meditate flower nature rainbow lucky',
    emojis: ['🧠','💡','🧘','🧖','💆','💅','🛀','🌈','🍀','🌿','🌱','🌸','🪷','🌷','🌼','🌻','💐','🕊️','☮️','☯️','🔮','🪬','🧿','♨️','🛌'] },
  { name: 'Health & body', keywords: 'health medicine pill doctor hospital heart body fit care medical',
    emojis: ['💊','💉','🩹','🩺','🦷','🫀','🫁','🩻','🏥','⚕️','🧬','🦠','🩸','🚑','🧫','🧪','🩼'] },
  { name: 'Food', keywords: 'food eat meal burger pizza fruit veg snack lunch dinner breakfast grocery cook',
    emojis: ['🍔','🍟','🍕','🌭','🥪','🌮','🌯','🥙','🧆','🥚','🍳','🥘','🍲','🥗','🍿','🧈','🧀','🥨','🥐','🥖','🍞','🥯','🥞','🧇','🍗','🍖','🥩','🥓','🍤','🍣','🍱','🍛','🍜','🍝','🍠','🍢','🍡','🍧','🍨','🍦','🥧','🧁','🍰','🎂','🍮','🍭','🍬','🍫','🍩','🍪','🍎','🍏','🍊','🍋','🍌','🍉','🍇','🍓','🫐','🍈','🍒','🍑','🥭','🍍','🥥','🥝','🍅','🍆','🥑','🥦','🥬','🥒','🌶️','🫑','🌽','🥕','🧄','🧅','🥔','🍠','🫛','🫚'] },
  { name: 'Drinks', keywords: 'drink coffee tea beer wine water juice cocktail cup bottle milk',
    emojis: ['☕','🍵','🧃','🥤','🧋','🍺','🍻','🥂','🍷','🥃','🍸','🍹','🍾','🥛','🫗','🧉','🍶'] },
  { name: 'Home & living', keywords: 'home house living room bed sofa door clean rent move furniture',
    emojis: ['🏠','🏡','🏘️','🏚️','🛏️','🛋️','🚪','🪑','🚽','🚿','🛁','🧴','🧷','🧹','🧺','🧻','🧼','🪣','🪟','🪞','🖼️','🕯️','🔦','🛒','🪤','🧸','🪆'] },
  { name: 'Travel & places', keywords: 'travel holiday trip plane beach mountain camp city building map vacation explore',
    emojis: ['✈️','🛫','🛬','🛩️','🚁','🚀','🛸','🏝️','🏖️','⛱️','🏔️','⛰️','🌋','🗻','🏕️','⛺','🏞️','🏜️','🏟️','🏛️','🏗️','🏙️','🌆','🌇','🌃','🌉','🗼','🗽','🎡','🎢','🎠','⛲','🏰','🏯','🗿','🧳','🗺️','🧭','🏨','🏖️'] },
  { name: 'Transport', keywords: 'car transport bus train bike taxi drive travel vehicle fuel traffic',
    emojis: ['🚗','🚕','🚙','🚌','🚎','🏎️','🚓','🚑','🚒','🚐','🛻','🚚','🚛','🚜','🛵','🏍️','🛺','🚲','🛴','🛹','🚆','🚄','🚅','🚈','🚂','🚊','🚉','🚇','🚝','⛵','🚤','🛥️','🛳️','⛴️','🚢','⚓','⛽','🚦','🚥','🚧','🚏'] },
  { name: 'Weather & sky', keywords: 'weather sun cloud rain snow storm moon star night day sky wind',
    emojis: ['☀️','🌤️','⛅','🌥️','☁️','🌦️','🌧️','⛈️','🌩️','🌨️','❄️','☃️','⛄','🌬️','💨','🌪️','🌫️','🌈','☔','💧','💦','🌊','🌙','🌛','🌜','🌚','🌝','🌞','⭐','🌟','💫','✨','☄️','🌠','🌡️'] },
  { name: 'Nature & plants', keywords: 'nature tree plant leaf flower green garden forest grow eco',
    emojis: ['🌲','🌳','🌴','🌵','🌾','🌿','☘️','🍀','🍁','🍂','🍃','🌱','🪴','🌷','🌹','🥀','🌺','🌸','🌼','🌻','💐','🍄','🪨','🌰','🪵'] },
  { name: 'Animals', keywords: 'animal pet dog cat bird fish bug wild zoo cute',
    emojis: ['🐶','🐱','🐭','🐹','🐰','🦊','🐻','🐼','🐨','🐯','🦁','🐮','🐷','🐸','🐵','🐔','🐧','🐦','🐤','🦆','🦅','🦉','🦇','🐺','🐗','🐴','🦄','🐝','🦋','🐌','🐞','🐜','🦗','🕷️','🐢','🐍','🦎','🐙','🦑','🦐','🦀','🐡','🐠','🐟','🐬','🐳','🐋','🦈','🐊','🐅','🐆','🦓','🦍','🐘','🦏','🐪','🐫','🦒','🐃','🐄','🐎','🐖','🐑','🐐','🦌','🐕','🐩','🐈','🐓','🦃','🕊️','🐇','🐿️','🦔','🦦','🦥','🦛'] },
  { name: 'Activities & sport', keywords: 'sport game play ball fitness gym run win match team exercise',
    emojis: ['⚽','🏀','🏈','⚾','🥎','🎾','🏐','🏉','🥏','🎱','🪀','🏓','🏸','🥅','🏒','🏑','🥍','🏏','⛳','🪁','🏹','🎣','🤿','🥊','🥋','🎽','🛹','🛼','🛷','⛸️','🥌','🎿','⛷️','🏂','🏋️','🤼','🤸','⛹️','🤺','🤾','🏌️','🏇','🧘','🏄','🏊','🤽','🚣','🧗','🚴','🚵'] },
  { name: 'Games & arts', keywords: 'game art music play fun creative paint movie camera draw dance',
    emojis: ['🎮','🕹️','🎲','🎰','🎳','🧩','♟️','🎭','🎨','🖌️','🖍️','🎬','🎤','🎧','🎼','🎹','🥁','🪘','🎷','🎺','🎸','🪕','🎻','🪗','📸','🎥','🎟️','🃏','🀄'] },
  { name: 'Tech & devices', keywords: 'tech phone computer laptop screen device app camera battery wifi gadget',
    emojis: ['📱','📲','💻','🖥️','⌨️','🖱️','🖲️','🖨️','📷','📸','📹','🎥','📽️','📺','📻','🎙️','⌚','📟','☎️','📞','📠','🔋','🪫','🔌','💡','🔦','🛰️','📡','💾','💿','📀','💽','🧮','🔍','🔎','🖲️'] },
  { name: 'Office & tools', keywords: 'office work tool file folder note pen paper mail box build fix wrench document report',
    emojis: ['📝','✏️','✒️','🖊️','🖋️','🖌️','🖍️','📏','📐','✂️','🗃️','🗄️','🗂️','📁','📂','🗒️','🗓️','📇','📋','📌','📍','📎','🖇️','🔖','🏷️','📦','📫','📪','📬','📭','📮','✉️','📧','📨','📩','📤','📥','📜','📃','📄','📑','🧾','🔧','🔨','⚒️','🛠️','⛏️','🪓','🔩','⚙️','🧰','🧲','⚗️','🧪','🔬','🔭','🪝','📚','📖','🔖'] },
  { name: 'Arrows & flow', keywords: 'arrow direction up down left right back next flow refresh repeat move',
    emojis: ['⬆️','↗️','➡️','↘️','⬇️','↙️','⬅️','↖️','↕️','↔️','↩️','↪️','⤴️','⤵️','🔃','🔄','🔙','🔚','🔛','🔜','🔝','🔼','🔽','▶️','◀️','🔀','🔁','🔂','⏩','⏪','⏭️','⏮️'] },
  { name: 'Symbols & math', keywords: 'symbol math plus minus times divide equals percent infinity number copyright trademark',
    emojis: ['➕','➖','✖️','➗','🟰','♾️','💲','💱','💯','🔢','#️⃣','*️⃣','0️⃣','1️⃣','2️⃣','3️⃣','4️⃣','5️⃣','6️⃣','7️⃣','8️⃣','9️⃣','🔟','©️','®️','™️','〽️','⚜️','🔱','⚛️','🔰','⭕','💠','♻️','✳️','✴️','❇️','☑️'] },
  { name: 'Celebration', keywords: 'party celebrate confetti balloon birthday fun champagne cheers graduate festive',
    emojis: ['🎉','🎊','🎈','🎁','🎀','🪅','🎆','🎇','🧨','✨','🥳','🍾','🥂','🪩','🎓','🎄','🎃','🪔','🎏','🎐','🎀'] },
  { name: 'People & family', keywords: 'people person family couple team group user profile baby work together',
    emojis: ['🧑','👩','👨','🧒','👶','👵','👴','👫','👬','👭','💑','👪','🧑‍🤝‍🧑','🙋','🙆','🙅','💁','🤷','🤦','🧑‍💻','👩‍💻','👨‍💻','💼','🧑‍🍳','🧑‍🎓','🧑‍🏫','🧑‍⚕️','👮','🕵️','🦸','🦹','🧑‍🚀','🧑‍🌾'] },
  { name: 'Flags', keywords: 'flag country world checkered race pride usa uk eu',
    emojis: ['🚩','🏁','🏳️','🏴','🏴‍☠️','🎌','🏳️‍🌈','🏳️‍⚧️','🇺🇸','🇬🇧','🇪🇺','🇨🇦','🇦🇺','🇩🇪','🇫🇷','🇪🇸','🇮🇹','🇳🇱','🇸🇪','🇨🇭','🇯🇵','🇰🇷','🇨🇳','🇮🇳','🇧🇷','🇲🇽','🇿🇦','🇦🇪'] },
];
