/**
 * Spendaily content packs — curated, on-brand copy and pills derived from the
 * blueprint. These seed the in-app Text-set and Pill libraries (merged once into
 * localStorage), so the user can browse and reuse them without regenerating.
 */
(function () {
  window.BRAND_CONTENT = window.BRAND_CONTENT || {};

  const A = (l1, l2) => [{ text: l1, accent: false }, { text: l2, accent: true }];

  const textSets = [
    // Daily number
    { eyebrow: 'TODAY', headline: A('Know what you can', 'safely spend today'), subtitle: 'One calm number every morning — your daily budget, done.' },
    { eyebrow: 'TODAY', headline: A('One number.', 'Every single day.'), subtitle: "See exactly what's safe to spend before you tap your card." },
    { eyebrow: 'SPEND', headline: A('Can I afford this?', 'Check one number.'), subtitle: 'Open Spendaily, glance once, and spend without second-guessing.' },
    { eyebrow: 'CLARITY', headline: A('Stop guessing', "today's budget."), subtitle: 'Your daily allowance updates the moment you log a spend.' },
    { eyebrow: 'DAILY', headline: A('Your whole budget,', 'in one number.'), subtitle: 'No spreadsheets, no categories to wrangle — just today’s limit.' },
    // Rollover
    { eyebrow: 'ROLLOVER', headline: A('Spent less today?', 'It rolls over 🎉'), subtitle: 'Leftover budget moves to tomorrow — or into a savings goal.' },
    { eyebrow: 'ROLLOVER', headline: A('Underspend today,', 'win tomorrow.'), subtitle: "Every pound you don't spend carries straight into tomorrow." },
    { eyebrow: 'CARRY', headline: A('Unspent money', 'keeps working.'), subtitle: "Roll it to tomorrow or send it to something you're saving for." },
    { eyebrow: 'BONUS', headline: A('Skipped the takeaway?', 'Bank the win.'), subtitle: "Yesterday's restraint becomes today's extra spending room." },
    { eyebrow: 'MIDNIGHT', headline: A('Every midnight,', 'it rolls itself.'), subtitle: 'Smart rollover moves leftover budget for you, automatically.' },
    // Goals
    { eyebrow: 'GOALS', headline: A('Your goals.', 'Within reach.'), subtitle: 'Every pound saved today funds something you actually want.' },
    { eyebrow: 'GOALS', headline: A('Turn one day', 'into a getaway.'), subtitle: 'Name a goal, set a date, and watch the progress ring fill up.' },
    { eyebrow: 'SAVE', headline: A("From 'I'm broke'", "to 'I'm saving'."), subtitle: 'Daily micro-savings stack into trips, tech and treats.' },
    { eyebrow: 'GOALS', headline: A('Every yes', 'has a why.'), subtitle: 'Tie daily spending to goals that actually matter to you.' },
    { eyebrow: 'CREATE', headline: A('Picture the goal.', 'Fund it daily.'), subtitle: 'Spendaily paces the saving so the target never feels far.' },
    // Calendar / streaks
    { eyebrow: 'CALENDAR', headline: A('Know where your', 'month stands.'), subtitle: 'A spending calendar of green days, streaks and small wins.' },
    { eyebrow: 'STREAKS', headline: A('No-spend days,', 'but make it fun.'), subtitle: 'Lock in streaks and gold stars instead of guilt.' },
    { eyebrow: 'MONTH', headline: A('See your month,', 'not your mess.'), subtitle: 'Spot overspending before it snowballs, day by day.' },
    { eyebrow: 'HABITS', headline: A('Money habits,', 'in colour.'), subtitle: 'Green days and gold stars that actually keep you on track.' },
    // Insights / payday
    { eyebrow: 'INSIGHTS', headline: A('Smart insights.', 'Zero spreadsheets.'), subtitle: 'Budget overview, rollover timeline and your safe-to-save number.' },
    { eyebrow: 'PAYDAY', headline: A('Am I okay', 'for payday?'), subtitle: 'See how much is left for the month in seconds, not sheets.' },
    { eyebrow: 'SCORE', headline: A('On track,', 'or drifting?'), subtitle: 'Your budget health score gives a clear yes or no.' },
    { eyebrow: 'MONTH-END', headline: A('End the month', 'with money left.'), subtitle: 'Daily limits and rollovers keep you out of payday panic.' },
    // Categories
    { eyebrow: 'CATEGORIES', headline: A('See where every', 'pound really goes.'), subtitle: 'Category donuts and trends that reveal the leaks.' },
    { eyebrow: 'CATEGORIES', headline: A('Find the leaks', 'in your spending.'), subtitle: 'Colour-coded categories show exactly where it adds up.' },
    // Logging
    { eyebrow: 'CAPTURE', headline: A('Log it in', 'five seconds.'), subtitle: 'Quick add, smart categories, or a one-tap daily total.' },
    { eyebrow: 'FAST', headline: A('Budgeting that fits', 'in a coffee queue.'), subtitle: "Open, log the amount, done before your order's ready." },
    { eyebrow: 'CAPTURE', headline: A('Spent without tracking?', 'Fix it fast.'), subtitle: 'Drop everything from today as one simple total.' },
    { eyebrow: 'SIMPLE', headline: A('No tracking', 'every coffee.'), subtitle: "Just drop today's total and Spendaily does the rest." },
    // Privacy
    { eyebrow: 'PRIVACY', headline: A('No bank linking.', 'Ever.'), subtitle: 'Private by design — track spending without connecting an account.' },
    { eyebrow: 'PRIVATE', headline: A('Your budget,', 'not your data.'), subtitle: 'Spendaily never connects to your bank. It stays on your phone.' },
    { eyebrow: 'SECURE', headline: A('Budget privately.', 'For real.'), subtitle: 'Manual tracking, no bank logins — just you and your number.' },
    { eyebrow: 'PRIVACY', headline: A('No bank link.', 'No worries.'), subtitle: 'Track spending without sharing card details with anyone.' },
    // Impulse control
    { eyebrow: 'CONTROL', headline: A('Before you tap,', 'check this.'), subtitle: 'Your daily number is a speedometer for impulse buys.' },
    { eyebrow: 'CONTROL', headline: A('Less oops,', "more 'I planned that'."), subtitle: 'Daily limits turn impulse spending into conscious choices.' },
    // Couples
    { eyebrow: 'TOGETHER', headline: A('Money,', 'managed together.'), subtitle: 'Budget as a couple without a single argument about money.' },
    { eyebrow: 'COUPLES', headline: A('Two people,', 'one calm plan.'), subtitle: 'Share a budget or split expenses — calm for both of you.' },
    // Flexible / complete
    { eyebrow: 'FLEXIBLE', headline: A('Paid differently', 'every month?'), subtitle: 'Log each payment and your daily budget builds itself.' },
    { eyebrow: 'FREELANCE', headline: A('Irregular income,', 'steady spending.'), subtitle: 'Flexible Pay smooths variable pay into a daily allowance.' },
    { eyebrow: 'COMPLETE', headline: A('Your full picture,', 'one daily number.'), subtitle: 'Salary, bills and savings become your true daily budget.' },
    // Themes / brand
    { eyebrow: 'YOUR STYLE', headline: A('Same clarity.', 'Your personality.'), subtitle: 'Five palettes, light or dark, live backgrounds — yours.' },
    { eyebrow: 'DESIGN', headline: A('Budgeting that', 'feels good.'), subtitle: "Soft gradients, gentle motion and themes you'll want to open." },
    { eyebrow: 'SPENDAILY', headline: A('What if your budget', 'was one number?'), subtitle: "The calm way to know what's safe to spend, every day." },
    { eyebrow: 'CALM', headline: A('Money anxiety,', 'quietly gone.'), subtitle: "Trade the 'where did it go?' feeling for one daily number." },
    { eyebrow: 'START', headline: A('Free to start.', 'Calm by design.'), subtitle: 'Begin in seconds — no bank connection, no fuss.' },
    // Creative batch — punchy, playful, emotional
    { eyebrow: 'TODAY', headline: A('Wake up to', 'one good number.'), subtitle: 'Your safe-to-spend amount, ready before your coffee.' },
    { eyebrow: 'CALM', headline: A('Budgeting,', 'minus the dread.'), subtitle: 'No charts to decode — just today’s number.' },
    { eyebrow: 'SPEND', headline: A('Treat yourself,', 'on purpose.'), subtitle: 'Know it fits today before you buy it.' },
    { eyebrow: 'ROLLOVER', headline: A('Today’s no,', 'tomorrow’s yes.'), subtitle: 'Skip a spend now and unlock more room tomorrow.' },
    { eyebrow: 'GOALS', headline: A('Small saves,', 'big somedays.'), subtitle: 'Tiny daily wins add up to the trip you keep picturing.' },
    { eyebrow: 'STREAKS', headline: A('Keep the', 'green going.'), subtitle: 'Every under-budget day extends your streak.' },
    { eyebrow: 'PROOF', headline: A('You’ve got this.', 'The numbers agree.'), subtitle: 'Watch your good days stack up on the calendar.' },
    { eyebrow: 'PRIVACY', headline: A('Just you', 'and your number.'), subtitle: 'No bank logins, no third parties, no tracking.' },
    { eyebrow: 'SIMPLE', headline: A('Five seconds.', 'That’s the habit.'), subtitle: 'Drop today’s total and get on with your day.' },
    { eyebrow: 'PAYDAY', headline: A('Make it', 'to payday.'), subtitle: 'A daily limit that quietly keeps you in the green.' },
    { eyebrow: 'IMPULSE', headline: A('Pause the', 'panic buy.'), subtitle: 'One glance tells you if it fits today.' },
    { eyebrow: 'COUPLES', headline: A('Budget together,', 'argue never.'), subtitle: 'One shared number, two calm minds.' },
    { eyebrow: 'FLEXIBLE', headline: A('Gig income?', 'No problem.'), subtitle: 'Your daily allowance rebuilds itself as you get paid.' },
    { eyebrow: 'INSIGHTS', headline: A('Clarity,', 'not clutter.'), subtitle: 'The few numbers that actually matter, daily.' },
    { eyebrow: 'CATEGORIES', headline: A('Where it goes,', 'finally clear.'), subtitle: 'A clean donut, no spreadsheet required.' },
    { eyebrow: 'CALENDAR', headline: A('A month of', 'small wins.'), subtitle: 'Green days and gold stars, all in one view.' },
    { eyebrow: 'START', headline: A('Try it tonight,', 'feel calmer tomorrow.'), subtitle: 'Set one number and see your first daily limit.' },
    { eyebrow: 'CONTROL', headline: A('In control,', 'not in a spreadsheet.'), subtitle: 'Budgeting that fits your life, not the other way round.' },
    { eyebrow: 'SAVE', headline: A('Spend less,', 'live more.'), subtitle: 'Underspend today and route it to what you love.' },
    { eyebrow: 'DESIGN', headline: A('Finance that', 'feels like calm.'), subtitle: 'Soft colours, gentle motion, zero stress.' },
    { eyebrow: 'MONEY', headline: A('Know your day,', 'own your money.'), subtitle: 'One number keeps every spend intentional.' },
    { eyebrow: 'HABIT', headline: A('The five-second', 'money habit.'), subtitle: 'Log today’s total and stay effortlessly on track.' },
    { eyebrow: 'TRUST', headline: A('Private', 'on purpose.'), subtitle: 'Manual by design — your data never leaves your phone.' },
    { eyebrow: 'REWARD', headline: A('Turn restraint', 'into rewards.'), subtitle: 'Every skipped spend nudges a goal closer.' },
    { eyebrow: 'TODAY', headline: A('One glance.', 'Total clarity.'), subtitle: 'Open the app, see your number, carry on.' },
    // ── Expanded pack — blueprint-grounded, 203 more sets ──
    { eyebrow: "ONE NUMBER", headline: A("Your whole budget,", "one calm number."), subtitle: "See what's safe to spend today, in one glance." },
    { eyebrow: "TODAY", headline: A("Can I afford this?", "Just check today."), subtitle: "Your daily number answers before you second-guess." },
    { eyebrow: "SPEND", headline: A("Spend today,", "no second-guessing."), subtitle: "Know your safe-to-spend number and enjoy the coffee." },
    { eyebrow: "EASE", headline: A("Less worry.", "One clear limit."), subtitle: "Your daily limit does the thinking, so you don't have to." },
    { eyebrow: "DAILY", headline: A("Today, you can", "spend up to..."), subtitle: "A fresh, honest number waiting for you each morning." },
    { eyebrow: "FOCUS", headline: A("Forget the spreadsheet.", "Remember one number."), subtitle: "The only figure you check before you buy." },
    { eyebrow: "ROLLOVER", headline: A("Under your limit", "The rest carries"), subtitle: "Spend under today and the leftover rolls into tomorrow." },
    { eyebrow: "LEFTOVER", headline: A("Didn't spend it?", "It rolls over"), subtitle: "Underspend and the rest carries to tomorrow, on its own." },
    { eyebrow: "GOALS", headline: A("Skip it today", "Fund a goal"), subtitle: "Send what you don't spend toward a real goal." },
    { eyebrow: "BALANCE", headline: A("Over one day?", "Under the next"), subtitle: "Overspend evens out gently across your period." },
    { eyebrow: "TODAY", headline: A("Hold back a little", "Gain a little"), subtitle: "The money you skip today waits for you tomorrow." },
    { eyebrow: "STREAKS", headline: A("Green day, again", "It stacks up"), subtitle: "A run of under-budget days builds a real cushion." },
    { eyebrow: "TOMORROW", headline: A("Tonight's leftover", "Tomorrow's room"), subtitle: "What you don't spend becomes breathing room tomorrow." },
    { eyebrow: "CARRY", headline: A("A quiet day", "A bigger tomorrow"), subtitle: "Spend under your limit and the rest carries forward." },
    { eyebrow: "PROGRESS", headline: A("Not spending", "counts too"), subtitle: "Roll what's left into a goal that slowly fills up." },
    { eyebrow: "GOALS", headline: A("Set a target,", "watch it fill"), subtitle: "Pick a goal and a date. A little each day fills the ring." },
    { eyebrow: "SAVINGS", headline: A("What you skip", "becomes a trip"), subtitle: "Send what you don't spend toward something real." },
    { eyebrow: "ROLLOVER", headline: A("Underspent today?", "Feed a goal"), subtitle: "Leftover from your daily number can flow into a goal." },
    { eyebrow: "FUNDED", headline: A("When it's full,", "it's yours"), subtitle: "Your goal fills up, then you make the purchase." },
    { eyebrow: "WHAT IF", headline: A("What if saving", "felt calm?"), subtitle: "Small daily amounts, quietly building toward your goal." },
    { eyebrow: "PROGRESS", headline: A("Small amounts,", "big goals"), subtitle: "A little each day, and your goal quietly grows." },
    { eyebrow: "STREAKS", headline: A("Stay under today", "Start a streak"), subtitle: "Every day under your limit grows your streak." },
    { eyebrow: "GREEN DAYS", headline: A("Come in under", "Day turns green"), subtitle: "Stay under your daily number and the day turns green." },
    { eyebrow: "MOMENTUM", headline: A("One good day", "Then another"), subtitle: "Small wins stack up, one calm day at a time." },
    { eyebrow: "CALENDAR", headline: A("Look back", "A row of green"), subtitle: "Watch your green days line up across the month." },
    { eyebrow: "WHAT IF", headline: A("What if today", "cost nothing?"), subtitle: "A no-spend day is a small win worth celebrating." },
    { eyebrow: "AGAIN", headline: A("Streak broke?", "Just begin again"), subtitle: "If a streak ends, no guilt — just start a fresh one." },
    { eyebrow: "PROGRESS", headline: A("Green adds up", "So does calm"), subtitle: "A calendar full of green days feels good to see." },
    { eyebrow: "CALENDAR", headline: A("See your whole month", "in green"), subtitle: "Every day you stayed under your limit, right there on the calendar." },
    { eyebrow: "GREEN DAYS", headline: A("A good day", "turns green"), subtitle: "Stay under your daily number and the day fills in with calm." },
    { eyebrow: "STREAKS", headline: A("One green day", "then another"), subtitle: "Watch your green days line up into a streak worth keeping." },
    { eyebrow: "ROLLOVER", headline: A("Underspend today", "tomorrow grows"), subtitle: "See yesterday's leftover roll right into today on the calendar." },
    { eyebrow: "NO-SPEND", headline: A("Spent nothing?", "That's a win"), subtitle: "No-spend days get their own mark, so small wins stay visible." },
    { eyebrow: "PER DAY", headline: A("Tap any day", "see the story"), subtitle: "What you spent and what rolled over, one calm day at a time." },
    { eyebrow: "PROGRESS", headline: A("Not perfect", "just greener"), subtitle: "A few more green days each month is progress you can see." },
    { eyebrow: "CALM", headline: A("No spreadsheets", "just a calendar"), subtitle: "Your whole budget, laid out as simple days you can read." },
    { eyebrow: "LOOK BACK", headline: A("Scroll the month", "feel the wins"), subtitle: "Look back on green days and streaks, and see how far you've come." },
    { eyebrow: "HEALTH", headline: A("Your money,", "one clear score"), subtitle: "Budget Health shows how your spending's really going." },
    { eyebrow: "CLARITY", headline: A("Not another", "cluttered dashboard"), subtitle: "One Budget Health score, no spreadsheet to decode." },
    { eyebrow: "CONSISTENCY", headline: A("Small steady days", "add up"), subtitle: "Consistency is a big part of your Budget Health." },
    { eyebrow: "CHECK-IN", headline: A("One glance,", "whole picture"), subtitle: "Check your Budget Health in a single calm moment." },
    { eyebrow: "CALM", headline: A("What if budgeting", "felt encouraging?"), subtitle: "Budget Health celebrates progress, never judges." },
    { eyebrow: "SCORE", headline: A("Numbers that", "cheer you on"), subtitle: "A gentle score that rewards steady, mindful spending." },
    { eyebrow: "REVIEW", headline: A("See the shape", "of your month"), subtitle: "Trends and past periods, all in one calm view." },
    { eyebrow: "CATEGORIES", headline: A("Curious where", "it all goes?"), subtitle: "A simple donut shows where it really lands." },
    { eyebrow: "DONUT", headline: A("One tap,", "one clear view."), subtitle: "Add optional colours and watch the donut fill in." },
    { eyebrow: "LEAKS", headline: A("Small spends", "quietly add up."), subtitle: "See the quiet leaks without tracking every coffee." },
    { eyebrow: "PATTERNS", headline: A("See the pattern,", "not the receipts."), subtitle: "Your donut reveals habits, no spreadsheets, no stress." },
    { eyebrow: "CLARITY", headline: A("A vague feeling", "to a clear picture."), subtitle: "Turn 'where did it all go?' into one calm donut." },
    { eyebrow: "STILL SIMPLE", headline: A("Detail when", "you want it."), subtitle: "Skip categories or add them, logging stays quick." },
    { eyebrow: "AT A GLANCE", headline: A("Your month,", "in one donut."), subtitle: "A calm view of where your money actually goes." },
    { eyebrow: "TOTAL", headline: A("One number", "for the day."), subtitle: "Log the total you spent and get on with your day." },
    { eyebrow: "DONE", headline: A("Log today.", "Back to living."), subtitle: "A quick daily total, then close the app and relax." },
    { eyebrow: "SIMPLE", headline: A("No itemizing.", "Just today's total."), subtitle: "Enter one number for the day and you're done." },
    { eyebrow: "QUICK", headline: A("Bought something?", "Add it, move on."), subtitle: "A few seconds now, no receipt-sorting later." },
    { eyebrow: "HABIT", headline: A("Too quick", "to put off."), subtitle: "So fast it becomes the easiest habit you keep." },
    { eyebrow: "FAST", headline: A("One entry.", "That's the whole log."), subtitle: "Log today's total spend in about five seconds." },
    { eyebrow: "5 SEC", headline: A("Five seconds.", "Fully logged."), subtitle: "That's all it takes to log the day's total." },
    { eyebrow: "PRIVACY", headline: A("No bank login.", "Ever."), subtitle: "Nothing links to your accounts. Your money stays yours." },
    { eyebrow: "MANUAL", headline: A("Log it yourself.", "In five seconds."), subtitle: "You enter today's total. No accounts connected, ever." },
    { eyebrow: "PRIVATE", headline: A("Your numbers.", "Your phone only."), subtitle: "Budgeting that never touches your bank or your data." },
    { eyebrow: "BY DESIGN", headline: A("Not connected.", "On purpose."), subtitle: "Manual logging keeps you mindful and your data private." },
    { eyebrow: "SIMPLE", headline: A("Type today's spend.", "Nothing else needed."), subtitle: "No bank connection required. Manual and mindful by design." },
    { eyebrow: "PAUSE", headline: A("Before you tap,", "check the number"), subtitle: "One glance tells you what's safe to spend today." },
    { eyebrow: "CHECK", headline: A("Room for this?", "One number knows"), subtitle: "Your daily limit answers before you reach your card." },
    { eyebrow: "CALM", headline: A("What if buying", "felt planned?"), subtitle: "Your daily number turns impulse into a choice." },
    { eyebrow: "AWAKE", headline: A("Tap your card", "with eyes open"), subtitle: "Know what's safe to spend today before you buy." },
    { eyebrow: "BREATHE", headline: A("Pause. Check.", "Then decide."), subtitle: "A calm beat between wanting it and buying it." },
    { eyebrow: "STILL FITS", headline: A("Buy it knowing", "it still fits"), subtitle: "Spend under your limit and the rest rolls over to tomorrow." },
    { eyebrow: "STREAK", headline: A("Skip the splurge,", "keep the streak"), subtitle: "Stay under today and watch the green days add up." },
    { eyebrow: "TOGETHER", headline: A("Two people", "One daily number"), subtitle: "Share one budget and one calm number for the day." },
    { eyebrow: "ONE POT", headline: A("Share everything", "Or keep it Split"), subtitle: "One Pot together or Split your own — you choose." },
    { eyebrow: "SPLIT", headline: A("Keep some yours", "Share the rest"), subtitle: "Split keeps personal money personal, shared money shared." },
    { eyebrow: "SHARED", headline: A("Same limit", "Same page"), subtitle: "You both see today's number, updated as you each log." },
    { eyebrow: "CALM", headline: A("Fewer money talks", "More easy days"), subtitle: "One shared number keeps the day light for both of you." },
    { eyebrow: "GOALS", headline: A("Save side by side", "Reach it together"), subtitle: "Send what you don't spend toward a goal you both want." },
    { eyebrow: "MANAGED", headline: A("Money, managed", "Together"), subtitle: "Couple's Budgeting keeps you both in sync, gently." },
    { eyebrow: "FAIR", headline: A("No more \"who paid?\"", "Just one number"), subtitle: "Shared spending stays clear, so nobody keeps score." },
    { eyebrow: "FLEXIBLE PAY", headline: A("Irregular income?", "Steady daily number."), subtitle: "Variable paydays still turn into one calm daily limit." },
    { eyebrow: "MANY PAYDAYS", headline: A("Two, three paydays?", "One daily limit."), subtitle: "Multiple paychecks fold into a single safe-to-spend number." },
    { eyebrow: "FREELANCE", headline: A("Income comes in waves.", "Spending stays calm."), subtitle: "Uneven pay smooths into a steady daily amount you can trust." },
    { eyebrow: "SELF-EMPLOYED", headline: A("Client pays late?", "Still safe to spend."), subtitle: "Your daily number works from the paydays you set." },
    { eyebrow: "BUILDS ITSELF", headline: A("Set your paydays.", "It does the rest."), subtitle: "Add variable or multiple paydays; the budget builds itself." },
    { eyebrow: "IN AND OUT", headline: A("Uneven paydays in.", "Steady days out."), subtitle: "Rolling 30-day windows keep your daily number honest." },
    { eyebrow: "SIDE HUSTLE", headline: A("Extra gig this week?", "Today's number grows."), subtitle: "Log new income and your safe-to-spend updates for you." },
    { eyebrow: "COMPLETE", headline: A("Rent, bills, savings", "all accounted for"), subtitle: "See your true daily number once the big stuff is handled." },
    { eyebrow: "REALITY", headline: A("Not what's in your bank,", "what's really yours"), subtitle: "Spend today knowing rent and bills are already covered." },
    { eyebrow: "PAYDAY", headline: A("Salary in,", "daily number out"), subtitle: "Your pay, fixed costs and savings shape one clear limit." },
    { eyebrow: "TRUE NUMBER", headline: A("The full picture,", "one honest number"), subtitle: "Salary, fixed costs and goals become your real daily limit." },
    { eyebrow: "COMPLETE BUDGETI", headline: A("Your whole month,", "one calm figure"), subtitle: "Everything that matters, shaped into what's safe to spend today." },
    { eyebrow: "MONTH-END", headline: A("Your whole month,", "in one look"), subtitle: "See what you saved and where it goes next." },
    { eyebrow: "SAVED", headline: A("Every period", "ends in a win"), subtitle: "A calm recap of what you kept this period." },
    { eyebrow: "NEXT", headline: A("What you saved", "finds a home"), subtitle: "Send this period's leftover toward a real goal." },
    { eyebrow: "STREAKS", headline: A("Count up the", "green days"), subtitle: "Your period in green days, streaks, and no-spend days." },
    { eyebrow: "FULL CIRCLE", headline: A("You started here.", "Look how far"), subtitle: "See how the period unfolded, day by calm day." },
    { eyebrow: "CELEBRATE", headline: A("Close the month", "feeling proud"), subtitle: "End every period with a quiet, honest win." },
    { eyebrow: "DONUT", headline: A("See where", "it all went"), subtitle: "A simple donut shows your spending, no spreadsheets." },
    { eyebrow: "CARRY ON", headline: A("This period's win", "starts the next"), subtitle: "Leftover carries forward, so each period begins ahead." },
    { eyebrow: "TODAY", headline: A("One number.", "Zero worry."), subtitle: "Your whole budget becomes a single, calm daily amount." },
    { eyebrow: "QUIET", headline: A("Money stress?", "Quietly gone."), subtitle: "See what's safe to spend today and breathe a little easier." },
    { eyebrow: "LET GO", headline: A("Log it in 5 sec.", "Then let go."), subtitle: "Note today's total, then relax while the app does the rest." },
    { eyebrow: "BREATHE", headline: A("Stop the guessing.", "Just check today."), subtitle: "No math, no dread, just today's safe-to-spend number." },
    { eyebrow: "MONTH-END", headline: A("No end-month dread.", "Just steady days."), subtitle: "Green days add up, so the last week stops feeling scary." },
    { eyebrow: "PEACE", headline: A("Budgeting, but", "it feels calm."), subtitle: "A warm, one-number app that never judges your spending." },
    { eyebrow: "PRIVACY", headline: A("No bank linking.", "Just peace of mind."), subtitle: "Manual by design, so your money stays calm and private." },
    { eyebrow: "CALM", headline: A("Where'd it all go?", "Now you always know."), subtitle: "Trade money worry for one calm number every day." },
    { eyebrow: "ONE NUMBER", headline: A("Skip the spreadsheet.", "Just one number."), subtitle: "Your whole budget, shown as a single daily number." },
    { eyebrow: "BEFORE / AFTER", headline: A("Twelve tabs open.", "Now, one number."), subtitle: "Trade the spreadsheet for a single safe-to-spend number." },
    { eyebrow: "CALM", headline: A("No math at night.", "Just your number."), subtitle: "The daily number does the math, so you don't have to." },
    { eyebrow: "LOG IT", headline: A("Don't itemize.", "Just log the total."), subtitle: "No need to track every coffee — just log today's total." },
    { eyebrow: "NO CHARTS", headline: A("Nothing to decode.", "Just today's number."), subtitle: "No charts or categories to untangle — just one clear number." },
    { eyebrow: "NO CATEGORIES", headline: A("Forget categories.", "One limit, that's all."), subtitle: "Skip the itemizing — one daily limit keeps you on track." },
    { eyebrow: "5 SECONDS", headline: A("Five seconds a day.", "Zero spreadsheets."), subtitle: "Logging takes about five seconds, with no categories to fill." },
    { eyebrow: "PAYDAY", headline: A("Make it to payday", "with money left"), subtitle: "Your daily limit keeps you in the green all the way to payday." },
    { eyebrow: "GREEN", headline: A("Quietly in", "the green"), subtitle: "One daily number keeps you steady from payday to payday." },
    { eyebrow: "TODAY", headline: A("Every day has", "a safe number"), subtitle: "Spend up to today's limit and payday still arrives with room." },
    { eyebrow: "ROLLOVER", headline: A("Underspend today", "cushion tomorrow"), subtitle: "Leftover money rolls into tomorrow, building a buffer for payday." },
    { eyebrow: "STEADY", headline: A("Same money", "steadier month"), subtitle: "Your daily number paces your spending so nothing runs out early." },
    { eyebrow: "CALM", headline: A("The 28th feels", "like the 1st"), subtitle: "One daily number keeps every week of the month feeling the same." },
    { eyebrow: "EASE", headline: A("Stop counting", "days till payday"), subtitle: "Know today's safe number and let payday take care of itself." },
    { eyebrow: "START", headline: A("One number.", "Set in seconds."), subtitle: "Add your budget once and see today's safe-to-spend number." },
    { eyebrow: "TODAY", headline: A("Your first", "daily limit"), subtitle: "See what you're safe to spend today, moments after you start." },
    { eyebrow: "FREE", headline: A("Free to start.", "Calm from day one."), subtitle: "Begin free, set one number, and let the daily budget do the rest." },
    { eyebrow: "PRIVACY", headline: A("No bank login.", "Nothing to connect."), subtitle: "Start in seconds, no accounts to link. Private by design." },
    { eyebrow: "CALM", headline: A("Money stress?", "One calm number."), subtitle: "Trade the mental math for a single safe-to-spend number." },
    { eyebrow: "WELCOME", headline: A("New here?", "Start in seconds."), subtitle: "Set one number and see today's limit before your coffee's done." },
    { eyebrow: "TRY IT", headline: A("Everything, free", "for a month"), subtitle: "Try goals, rollover and more free for a month. No pressure." },
    { eyebrow: "PALETTES", headline: A("Six palettes.", "Pick your calm."), subtitle: "Choose the colours that make budgeting feel like yours." },
    { eyebrow: "DARK MODE", headline: A("Bright by day,", "soft by night."), subtitle: "Light or dark, your budget looks good at any hour." },
    { eyebrow: "MOTION", headline: A("Gentle motion,", "never noise."), subtitle: "Soft animation that never rushes or overwhelms." },
    { eyebrow: "THEMES", headline: A("Your mood,", "your theme."), subtitle: "Switch palettes whenever the feeling changes." },
    { eyebrow: "DAILY", headline: A("One number,", "beautifully shown."), subtitle: "Your safe-to-spend today, framed to feel calm." },
    { eyebrow: "BREATHE", headline: A("A budget", "that breathes."), subtitle: "Living wallpapers add a slow, gentle sense of ease." },
    { eyebrow: "DELIGHT", headline: A("Budgeting,", "but lovely."), subtitle: "Six palettes, soft motion, and a look you'll enjoy." },
    { eyebrow: "GOALS", headline: A("Skip it today", "Book it later"), subtitle: "Send what you don't spend toward a trip you'll actually take." },
    { eyebrow: "DREAM", headline: A("That thing you want", "It's a goal now"), subtitle: "Give it a target and a date, then watch it slowly fill up." },
    { eyebrow: "TRIP", headline: A("Underspend today", "Fly there sooner"), subtitle: "Leftover days quietly add up to the getaway you want." },
    { eyebrow: "GADGET", headline: A("Want the new one?", "Let it fill up"), subtitle: "Set it as a goal and buy it the day it's funded." },
    { eyebrow: "ROLLOVER", headline: A("Today's leftover", "Tomorrow's plans"), subtitle: "What you don't spend rolls forward, toward what you want." },
    { eyebrow: "STREAKS", headline: A("A no-spend day?", "One step closer"), subtitle: "Every quiet day nudges your goal a little nearer." },
    { eyebrow: "SUMMER", headline: A("A little each day", "A lot by summer"), subtitle: "Leftover budget stacks up toward the summer you want." },
    { eyebrow: "CHOOSE", headline: A("Keep the change", "Choose the goal"), subtitle: "Point what you don't spend at the goal that matters most." },
    { eyebrow: "SWITCH", headline: A("Tried every app?", "Try one number."), subtitle: "One daily number replaces the whole complicated setup." },
    { eyebrow: "COFFEE", headline: A("Stop logging", "every coffee."), subtitle: "Log today's total in about five seconds. That's the whole job." },
    { eyebrow: "ROLLOVER", headline: A("Underspend today?", "It rolls over."), subtitle: "What you don't spend carries into tomorrow, on its own." },
    { eyebrow: "PRIVACY", headline: A("No bank login.", "Nothing to sync."), subtitle: "Manual by design, so your money stays private and yours." },
    { eyebrow: "NO CHORE", headline: A("No categories.", "No spreadsheets."), subtitle: "Skip the setup and just see what's safe to spend today." },
    { eyebrow: "BEFORE / AFTER", headline: A("Charts and reports?", "Just today's limit."), subtitle: "Trade the busy dashboard for one calm number you can trust." },
    { eyebrow: "WHAT IF", headline: A("What if budgeting", "took five seconds?"), subtitle: "Enter today's total spend and you're done until tomorrow." },
    { eyebrow: "CALM", headline: A("Less tracking.", "More breathing room."), subtitle: "One number keeps you on track without the daily fuss." },
    { eyebrow: "RETRY", headline: A("Fell off budgeting?", "This one sticks."), subtitle: "Five-second logging is easy enough to actually keep up." },
    { eyebrow: "FIVE SECONDS", headline: A("Log today's total", "in five seconds"), subtitle: "One quick number a day. No itemizing, no receipts." },
    { eyebrow: "CALM", headline: A("No spreadsheets.", "Just today's number."), subtitle: "See what you can spend, then get on with your day." },
    { eyebrow: "NO FUSS", headline: A("Skip the tracking.", "Log one total."), subtitle: "No need to track every coffee. Just today's total spend." },
    { eyebrow: "STREAKS", headline: A("One log a day", "builds a streak"), subtitle: "Log daily and watch your green days line up." },
    { eyebrow: "ONE NUMBER", headline: A("Your whole budget,", "one daily number"), subtitle: "Everything you can spend today, in a single number." },
    { eyebrow: "GLANCE", headline: A("How much today?", "One glance tells you"), subtitle: "Open Spendaily and your daily limit is right there." },
    { eyebrow: "TOMORROW", headline: A("Log tonight,", "wake up ahead"), subtitle: "Underspend today and the rest rolls into tomorrow." },
    { eyebrow: "CONTROL", headline: A("Your money,", "your call."), subtitle: "You set the limit and decide how today goes." },
    { eyebrow: "DECIDE", headline: A("One number.", "You're in charge."), subtitle: "Your whole budget, in a single daily figure you own." },
    { eyebrow: "STEADY", headline: A("No autopilot.", "Just you."), subtitle: "Manual by design, so every choice stays yours." },
    { eyebrow: "CHOICE", headline: A("Spend it now", "or save it."), subtitle: "Underspend today and send the rest toward a goal." },
    { eyebrow: "EMPOWER", headline: A("You lead.", "It follows."), subtitle: "Your daily number bends to the choices you make." },
    { eyebrow: "CALM", headline: A("No pressure.", "Your pace."), subtitle: "Spend under your limit and the rest carries over." },
    { eyebrow: "PRIVACY", headline: A("No bank login.", "You stay in control."), subtitle: "Manual entry keeps your money yours alone." },
    { eyebrow: "TODAY", headline: A("Know your limit.", "Then choose."), subtitle: "See what's safe to spend, then spend it your way." },
    { eyebrow: "DIRECT", headline: A("Set the number.", "Run your day."), subtitle: "Log today's spend in seconds and stay on track." },
    { eyebrow: "GOALS", headline: A("You pick the goal.", "It fills up."), subtitle: "Send what you don't spend toward what matters." },
    { eyebrow: "SIMPLE", headline: A("Budgets got complex.", "This one didn't."), subtitle: "Skip the spreadsheets. Just today's number, clear and calm." },
    { eyebrow: "5 SECONDS", headline: A("Log today's spend", "in five seconds"), subtitle: "One total, no itemizing — done before your coffee's cold." },
    { eyebrow: "CLARITY", headline: A("Less to track.", "More clarity."), subtitle: "Fewer numbers, more calm — you always know where you stand." },
    { eyebrow: "SETUP", headline: A("Set it once.", "See it daily."), subtitle: "No fiddly setup — just a daily number that rolls over." },
    { eyebrow: "HOW MUCH", headline: A("How much today?", "One number answers."), subtitle: "Ask once, glance once — that's the whole system." },
    { eyebrow: "REAL LIFE", headline: A("Some months", "just don't fit"), subtitle: "Your budget bends with real life, no perfect month required." },
    { eyebrow: "PAYDAYS", headline: A("Paid whenever?", "Still one number"), subtitle: "Variable or multiple paydays, your daily budget builds itself." },
    { eyebrow: "UP AND DOWN", headline: A("Good week, lean week", "one calm number"), subtitle: "Every day still shows what's safe to spend today." },
    { eyebrow: "FREELANCE", headline: A("Income comes in", "waves, not weeks"), subtitle: "Spread an uneven month into a steady daily limit." },
    { eyebrow: "ROLLING", headline: A("Forget the 1st", "of the month"), subtitle: "A rolling 30-day window that follows real life, not the calendar." },
    { eyebrow: "TIPS & GIGS", headline: A("Cash that changes", "a number that flexes"), subtitle: "Tips, gigs, side work, all smoothed into one daily limit." },
    { eyebrow: "NO GUILT", headline: A("Went over today?", "No worries."), subtitle: "Tomorrow's number simply adjusts, and you carry on." },
    { eyebrow: "FORGIVING", headline: A("One day off?", "It evens out."), subtitle: "Overspend today and it gently rolls into tomorrow." },
    { eyebrow: "NO SHAME", headline: A("Missed a day?", "Just pick it up."), subtitle: "No broken-streak guilt, only a fresh start." },
    { eyebrow: "CALM", headline: A("Not a chore.", "Not a lecture."), subtitle: "Just today's number, logged in about five seconds." },
    { eyebrow: "EASY", headline: A("No itemizing.", "No judgment."), subtitle: "Log today's total spend and get on with your day." },
    { eyebrow: "PERMISSION", headline: A("You're allowed", "to spend."), subtitle: "Know today's safe amount and enjoy it, guilt-free." },
    { eyebrow: "PATIENT", headline: A("Off track?", "You'll be fine."), subtitle: "One gentle number guides you back, no scolding." },
    { eyebrow: "ROLLOVER", headline: A("Skip it today", "Spend it tomorrow"), subtitle: "What you don't spend rolls into tomorrow's number." },
    { eyebrow: "GOALS", headline: A("Say no today", "Yes to your goal"), subtitle: "Send what you skip toward a real goal." },
    { eyebrow: "SAVINGS", headline: A("Skip the extra", "Fund the goal"), subtitle: "Leftover money can fill up a goal you actually want." },
    { eyebrow: "CALM", headline: A("No guilt here", "Just green days"), subtitle: "Small wins add up, one calm green day at a time." },
    { eyebrow: "HEALTH", headline: A("Spend a little less", "Budget Health climbs"), subtitle: "A little restraint today gently lifts Budget Health." },
    { eyebrow: "REWARD", headline: A("Restraint, rewarded", "Not restricted"), subtitle: "Spend under your limit and the rest rolls over." },
    { eyebrow: "NEW YEAR", headline: A("New year,", "one number."), subtitle: "Start the year with a calm daily number to spend to." },
    { eyebrow: "JANUARY", headline: A("After the holidays,", "a fresh reset."), subtitle: "Spent more in December? Your daily number evens out." },
    { eyebrow: "HOLIDAYS", headline: A("Gift season", "without the worry."), subtitle: "See what's safe to spend today, all December long." },
    { eyebrow: "SUMMER", headline: A("That summer trip?", "Give it a goal."), subtitle: "Send what you don't spend toward a real trip fund." },
    { eyebrow: "SCHOOL", headline: A("Back-to-school", "sorted, calmly."), subtitle: "Big list, one daily limit, and no need to itemize." },
    { eyebrow: "SPRING", headline: A("Spring clean", "your budget."), subtitle: "One calm number quietly replaces the spreadsheet." },
    { eyebrow: "AUTUMN", headline: A("Cozy season,", "steady spending."), subtitle: "A calm daily number as the days get shorter." },
    { eyebrow: "STREAKS", headline: A("This year,", "build a streak."), subtitle: "Green days add up, one calm day at a time." },
    { eyebrow: "ROLLOVER", headline: A("Big holiday week?", "Tomorrow evens out."), subtitle: "Overspend today and it gently carries into tomorrow." },
    { eyebrow: "CALM", headline: A("Long summer days,", "one simple number."), subtitle: "Enjoy the season knowing today's limit at a glance." },
    { eyebrow: "TOGETHER", headline: A("Holidays add up.", "Share one pot."), subtitle: "Plan seasonal spending together with Couple's Budgeting." },

  ];

  const pills = [
    // Daily number
    { emoji: '💷', title: 'Daily limit', subtitle: '£108.34' },
    { emoji: '🟢', title: 'Safe to spend', subtitle: "today's number" },
    { emoji: '📅', title: 'Today', subtitle: 'one calm number' },
    { emoji: '⏰', title: 'Every morning', subtitle: 'a fresh number' },
    { emoji: '💡', title: 'Know your limit', subtitle: 'before you spend' },
    { emoji: '🛟', title: 'Spend safely', subtitle: 'never over' },
    // Rollover
    { emoji: '🔁', title: 'Smart Rollover', subtitle: 'set & forget' },
    { emoji: '🎉', title: '+£42.53', subtitle: 'to tomorrow' },
    { emoji: '🌙', title: 'Every midnight', subtitle: 'rolls automatically' },
    { emoji: '💜', title: 'Saved £31.03', subtitle: 'ready to route' },
    { emoji: '💵', title: '+£93.36', subtitle: 'rolled over' },
    { emoji: '📈', title: 'Carries forward', subtitle: 'never lost' },
    // Goals
    { emoji: '🎯', title: 'Goal progress', subtitle: '+2.4%' },
    { emoji: '✈️', title: 'Thailand trip', subtitle: '17% funded' },
    { emoji: '⌛', title: '6mo left', subtitle: 'ETA countdown' },
    { emoji: '👜', title: 'Bag · 100%', subtitle: 'goal purchased' },
    { emoji: '🏆', title: '1 achieved', subtitle: 'goals hit' },
    { emoji: '🎧', title: 'New headphones', subtitle: 'saving up' },
    { emoji: '🏝️', title: 'Dream trip', subtitle: 'funded daily' },
    { emoji: '🚀', title: 'Saving fast', subtitle: 'ahead of plan' },
    // Streaks / no-spend
    { emoji: '🔥', title: '4-day streak', subtitle: 'keep it going' },
    { emoji: '⭐', title: '7 no-spend days', subtitle: 'this month' },
    { emoji: '⚡', title: 'Streaks', subtitle: 'auto-protected' },
    { emoji: '✅', title: 'On track', subtitle: '4 days in a row' },
    { emoji: '🟩', title: '26 days under', subtitle: 'budget this month' },
    { emoji: '🥇', title: 'Best streak', subtitle: '12 days' },
    // Calendar
    { emoji: '📅', title: 'Payday cycles', subtitle: 'or calendar month' },
    { emoji: '🗓️', title: '£37.84', subtitle: 'daily average' },
    { emoji: '💚', title: '£832.47', subtitle: 'tracked this month' },
    // Insights
    { emoji: '💯', title: 'Budget score', subtitle: '90% this period' },
    { emoji: '🧠', title: 'Smart insights', subtitle: 'daily guidance' },
    { emoji: '📊', title: 'Projected saving', subtitle: '£67.53' },
    { emoji: '🧾', title: 'Month-end review', subtitle: 'what you saved' },
    // Categories
    { emoji: '📦', title: '8 categories', subtitle: 'auto-organised' },
    { emoji: '🚗', title: 'Transport · 13%', subtitle: '£105 this month' },
    { emoji: '🍴', title: 'Food · 12%', subtitle: '£100 this month' },
    { emoji: '🛒', title: 'Groceries', subtitle: '' },
    { emoji: '🛍️', title: 'Shopping', subtitle: '' },
    { emoji: '🍔', title: 'Food & Dining', subtitle: '' },
    { emoji: '☕', title: 'Coffee runs', subtitle: 'add up fast' },
    // Logging
    { emoji: '⏱️', title: 'Under 5 seconds', subtitle: 'quick add' },
    { emoji: '🧾', title: 'Daily total mode', subtitle: 'one tap, done' },
    { emoji: '👆', title: 'Three taps', subtitle: "and you're done" },
    { emoji: '📝', title: 'Log the total', subtitle: 'skip the receipts' },
    // Privacy
    { emoji: '🔒', title: 'No bank access', subtitle: 'private by design' },
    { emoji: '🛡️', title: 'No tracking', subtitle: 'your data stays yours' },
    { emoji: '✋', title: 'Manual control', subtitle: 'you own your data' },
    { emoji: '🔐', title: 'Private & secure', subtitle: 'nothing linked' },
    // Currency / languages
    { emoji: '🌍', title: '60+ currencies', subtitle: '14 languages' },
    { emoji: '🌐', title: '14 languages', subtitle: 'fully localised' },
    // Premium / free
    { emoji: '⭐', title: 'Free to start', subtitle: 'Premium optional' },
    { emoji: '💎', title: 'Premium', subtitle: 'save smarter' },
    { emoji: '🆓', title: 'Core is free', subtitle: 'forever' },
    { emoji: '🎁', title: '1-month trial', subtitle: 'cancel anytime' },
    // Couples / flexible
    { emoji: '💑', title: 'Couples budgeting', subtitle: 'one shared pot' },
    { emoji: '🤝', title: 'Split expenses', subtitle: 'no awkward maths' },
    { emoji: '📆', title: 'Flexible Pay', subtitle: 'any payday schedule' },
    { emoji: '💼', title: 'Variable income', subtitle: 'handled' },
    // Emotional / proof
    { emoji: '💛', title: 'Calm by design', subtitle: 'no money stress' },
    { emoji: '😌', title: 'Less anxiety', subtitle: 'more control' },
    { emoji: '🌟', title: 'Loved by budgeters', subtitle: '5 stars' },
    { emoji: '❤️', title: '"Feels like a game"', subtitle: '— Priya S.' },
    { emoji: '👍', title: 'Stay on track', subtitle: 'without the chore' },
    // Themes / misc
    { emoji: '🎨', title: '6 palettes', subtitle: 'light, dark & live' },
    { emoji: '🌗', title: 'Light & dark', subtitle: 'your choice' },
    { emoji: '🔔', title: 'Gentle reminders', subtitle: 'never naggy' },
    { emoji: '📲', title: 'Always with you', subtitle: 'budget in your pocket' },
  ];

  // Panorama gradients — one master gradient flowing across all screens. Tuned
  // so the hue clearly travels screen-to-screen while staying soft for text.
  const panoramas = [
    { name: 'Spendaily', colors: ['#C7B8F2', '#D9C2F0', '#EBC6E6', '#F3C9D6', '#F6CFC2', '#E9CBE6', '#CBC2F2'] },
    { name: 'Aurora', colors: ['#BFD0F5', '#C7C2F2', '#D8C2EE', '#EAC6E2', '#C9E3D6', '#BFD0F5'] },
    { name: 'Sunrise', colors: ['#FAD7B8', '#F8C9C2', '#F4C2D2', '#E6C2EC', '#CFC6F2', '#BFD0F5'] },
    { name: 'Candy Pop', colors: ['#F4C2DC', '#E3C2F0', '#C9C6F2', '#BFD9F2', '#C2EAE0', '#F4D9C2'] },
    { name: 'Lagoon', colors: ['#A9E0DE', '#B8D8F0', '#C7C9F0', '#D8C2EC', '#EAC6DE', '#F6CFC2'] },
    { name: 'Berry Bloom', colors: ['#C9B2E8', '#E0AEDC', '#F0AEC6', '#F6BBC0', '#F2C9C2', '#E6C2E6'] },
    { name: 'Peach Sorbet', colors: ['#FBD7C2', '#F9CFC9', '#F6C9D6', '#EFC9E2', '#DCC9F0', '#C9D2F2'] },
    { name: 'Mint Lilac', colors: ['#C2EBDD', '#CFE6E6', '#D9DCF0', '#E2CFEE', '#EFC9E2', '#F6CFD2'] },
    { name: 'Midnight', colors: ['#3A2A66', '#4A2A78', '#5A2A7C', '#43286B', '#2E2160', '#241A52'] },
    { name: 'Dusk', colors: ['#5B4B8A', '#7A5A9E', '#9A5A95', '#B0628A', '#8A5A9E', '#5B4B8A'] },
  ];

  window.BRAND_CONTENT.spendaily = { textSets, pills, panoramas };
})();
